# Generated by Django 4.0.6 on 2022-07-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_variacao_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='estoque',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
